stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd appVue
    — npm install
    - npm run dev
    - cd ..
  artifacts:
    paths:
      - appVue/dist/
  only:
    - master

deploy:
  stage: deploy
  script:
    - python3 manage.py runserver 0.0.0.0:8000
  only:
    - master