# Generated by Django 2.2.6 on 2019-10-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50)),
                ('filepath', models.FilePathField()),
                ('codefile', models.FileField(upload_to=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
